CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE TABLE item (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    no VARCHAR(100) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    spec VARCHAR(255) NOT NULL,

    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);